/**
 * server/learning/registeredPlayers.js
 * ------------------------------------------------
 * 2026年8月・優先順位⑦「選手情報を毎日更新」で使う、日次更新の対象選手一覧。
 *
 * 新しく発明したリストではなく、index.html の PLAYERS(アプリが元々持っている
 * 手動キュレーション済みの選手データベース、107名)から
 * key / 日本語名 / 英語名 / 所属クラブ を機械的に写したものです
 * (scripts/gen_registered_players.js で再生成できます)。
 *
 * staticFoot / staticContractNote について:
 *   利き足と契約情報は API-Football の /players レスポンスに存在しません
 *   (player オブジェクトは id/name/age/birth/nationality/height/weight/
 *   injured/photo のみ。server/learning/playerFeatures.js の冒頭に既に
 *   確認済みとして記録されています)。つまり「毎日APIから更新する」ことが
 *   構造的に不可能な項目です。ただしアプリ内には手動登録された値が存在するため、
 *   「APIからは更新できないが、アプリが持っている手動データではこうなっている」
 *   と正直に併記できるよう、ここに写しています(手動データのため最新性は
 *   保証されません)。
 */
const REGISTERED_PLAYERS = [
  {"key":"messi","nameJa":"リオネル・メッシ","nameEn":"Lionel Messi","clubJa":"インテル・マイアミ","staticFoot":"左足","staticContractNote":"フリー移籍・前所属:パリ・サンジェルマン・2023年7月"},
  {"key":"ronaldo","nameJa":"クリスティアーノ・ロナウド","nameEn":"Cristiano Ronaldo","clubJa":"アル・ナスル","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:マンチェスター・ユナイテッド・2023年1月"},
  {"key":"mbappe","nameJa":"キリアン・エムバペ","nameEn":"Kylian Mbappé","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:パリ・サンジェルマン・2024年7月"},
  {"key":"haaland","nameJa":"アーリング・ハーランド","nameEn":"Erling Haaland","clubJa":"マンチェスター・シティ","staticFoot":"左足","staticContractNote":"release_clause・前所属:ボルシア・ドルトムント・2022年7月"},
  {"key":"debruyne","nameJa":"ケビン・デ・ブライネ","nameEn":"Kevin De Bruyne","clubJa":"ナポリ","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:マンチェスター・シティ・2025年6月"},
  {"key":"bsilva","nameJa":"ベルナルド・シウバ","nameEn":"Bernardo Silva","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:マンチェスター・シティ・2026年6月"},
  {"key":"yamal","nameJa":"ラミン・ヤマル","nameEn":"Lamine Yamal","clubJa":"FCバルセロナ","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"kubo","nameJa":"久保建英","nameEn":"Takefusa Kubo","clubJa":"レアル・ソシエダ","staticFoot":"左足","staticContractNote":"fee・前所属:レアル・マドリード・2023年8月"},
  {"key":"urbig","nameJa":"ヨナス・ウルビッヒ","nameEn":"Jonas Urbig","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"fee・前所属:1.FCケルン・2025年1月"},
  {"key":"neuer","nameJa":"マヌエル・ノイアー","nameEn":"Manuel Neuer","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"fee・前所属:FCシャルケ04・2011年"},
  {"key":"ulreich","nameJa":"スヴェン・ウルライヒ","nameEn":"Sven Ulreich","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:VfBシュトゥットガルト・2015年7月"},
  {"key":"baertl","nameJa":"ヤニス・ベルトル","nameEn":"Jannis Bärtl","clubJa":"バイエルン・ミュンヘンII","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"prescott","nameJa":"レナード・プレスコット","nameEn":"Leonard Prescott","clubJa":"バイエルン・ミュンヘンU19","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"klanac","nameJa":"レオン・クラナック","nameEn":"Leon Klanac","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"upamecano","nameJa":"ダヨ・ウパメカノ","nameEn":"Dayot Upamecano","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"release_clause・前所属:RBライプツィヒ・2021年7月"},
  {"key":"kimminjae","nameJa":"キム・ミンジェ","nameEn":"Kim Min-jae","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"fee・前所属:SSCナポリ・2023年7月"},
  {"key":"tah","nameJa":"ヨナタン・ター","nameEn":"Jonathan Tah","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:バイエル・レバークーゼン・2025年5月"},
  {"key":"kimmich","nameJa":"ヨシュア・キミッヒ","nameEn":"Joshua Kimmich","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"undisclosed・前所属:RBライプツィヒ(下部組織)・2015年"},
  {"key":"davies","nameJa":"アルフォンソ・デイヴィス","nameEn":"Alphonso Davies","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"fee・前所属:バンクーバー・ホワイトキャップスFC(MLS)・2018年7月"},
  {"key":"ito","nameJa":"伊藤洋輝","nameEn":"Hiroki Ito","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"fee・前所属:VfBシュトゥットガルト・2024年6月"},
  {"key":"boey","nameJa":"サシャ・ボエ","nameEn":"Sacha Boey","clubJa":"バイエルン・ミュンヘン(2025-26はガラタサライへ期限付き移籍)","staticFoot":"不明","staticContractNote":"fee・前所属:ガラタサライ・2024年1月"},
  {"key":"buchmann","nameJa":"タレク・ブッフマン","nameEn":"Tarek Buchmann","clubJa":"バイエルン・ミュンヘン(1.FCニュルンベルクへ期限付き移籍中)","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"ofli","nameJa":"デニズ・エムレ・オフリ","nameEn":"Deniz Emre Ofli","clubJa":"バイエルン・ミュンヘン(カールスルーアSCへ期限付き移籍中)","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"manuba","nameJa":"ヴィンセント・ウーゴ・マヌバ","nameEn":"Vincent Ugo Manuba","clubJa":"バイエルン・ミュンヘンII","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"stanisic","nameJa":"ヨシプ・スタニシッチ","nameEn":"Josip Stanišić","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"brown","nameJa":"ナサニエル・ブラウン","nameEn":"Nathaniel Brown","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"fee・前所属:アイントラハト・フランクフルト・2026年7月"},
  {"key":"musiala","nameJa":"ジャマル・ムシアラ","nameEn":"Jamal Musiala","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"undisclosed・前所属:チェルシー(下部組織)・2019年2月"},
  {"key":"palhinha","nameJa":"ジョアン・パリーニャ","nameEn":"João Palhinha","clubJa":"バイエルン・ミュンヘン(移籍の可能性が報じられている)","staticFoot":"右足","staticContractNote":"fee・前所属:フラム・2024年7月"},
  {"key":"zaragoza","nameJa":"ブライアン・サラゴサ","nameEn":"Bryan Zaragoza","clubJa":"バイエルン・ミュンヘン(売却が検討されていると報じられている)","staticFoot":"左足","staticContractNote":"fee・前所属:グラナダCF・2024年1月"},
  {"key":"ibrahimovic","nameJa":"アリヨン・イブラヒモヴィッチ","nameEn":"Arijon Ibrahimović","clubJa":"バイエルン・ミュンヘン(2026-27シーズンからトップチームに編入)","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"bischof","nameJa":"トム・ビショフ","nameEn":"Tom Bischof","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"フリー移籍・前所属:ホッフェンハイム・2025年1月"},
  {"key":"laimer","nameJa":"コンラート・ライマー","nameEn":"Konrad Laimer","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:RBライプツィヒ・2023年6月"},
  {"key":"dellarovere","nameJa":"グイド・デッラ・ローヴェレ","nameEn":"Guido Della Rovere","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"undisclosed・前所属:クレモネーゼ(イタリア)・2025年2月頃"},
  {"key":"fernandez","nameJa":"ハビ・フェルナンデス","nameEn":"Javi Fernández","clubJa":"バイエルン・ミュンヘン(1.FCニュルンベルクへ期限付き移籍中)","staticFoot":"不明","staticContractNote":"undisclosed・前所属:アトレティコ・マドリード(下部組織)・2022年11月"},
  {"key":"saibari","nameJa":"イスマエル・サイバリ","nameEn":"Ismael Saibari","clubJa":"バイエルン・ミュンヘン(2026年7月加入)","staticFoot":"不明","staticContractNote":"fee・前所属:PSVアイントホーフェン・2026年7月"},
  {"key":"chavez","nameJa":"フェリペ・チャベス","nameEn":"Felipe Chávez","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"undisclosed・前所属:バイエルン下部組織"},
  {"key":"karl","nameJa":"レナート・カール","nameEn":"Lennart Karl","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"homegrown"},
  {"key":"pavlovic","nameJa":"アレクサンダル・パヴロヴィッチ","nameEn":"Aleksandar Pavlović","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"daiber","nameJa":"ダヴィド・サントス・ダイバー","nameEn":"David Santos Daiber","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"cardozo","nameJa":"マイコン・カルドソ","nameEn":"Maycon Cardozo","clubJa":"バイエルン・ミュンヘン","staticFoot":"不明","staticContractNote":"homegrown・2025年2月"},
  {"key":"gnabry","nameJa":"セルジュ・ニャブリ","nameEn":"Serge Gnabry","clubJa":"バイエルン・ミュンヘン","staticFoot":"両足","staticContractNote":"フリー移籍・前所属:ヴェルダー・ブレーメン・2017年"},
  {"key":"kane","nameJa":"ハリー・ケイン","nameEn":"Harry Kane","clubJa":"バイエルン・ミュンヘン","staticFoot":"右足","staticContractNote":"fee・前所属:トッテナム・ホットスパー・2023年8月"},
  {"key":"diaz","nameJa":"ルイス・ディアス","nameEn":"Luis Díaz","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"fee・前所属:リヴァプール・2025年7月"},
  {"key":"olise","nameJa":"ミカエル・オリーズ","nameEn":"Michael Olise","clubJa":"バイエルン・ミュンヘン","staticFoot":"左足","staticContractNote":"fee・前所属:クリスタル・パレス・2024年7月"},
  {"key":"sieb","nameJa":"アルミンド・ジープ","nameEn":"Armindo Sieb","clubJa":"バイエルン・ミュンヘン(マインツ05へ期限付き移籍中)","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"assomo","nameJa":"バスティアン・アッソモ","nameEn":"Bastian Assomo","clubJa":"バイエルン・ミュンヘンII","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"araya","nameJa":"ダビド・ラヤ","nameEn":"David Raya","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:ブレントフォード・2024年7月"},
  {"key":"kepa","nameJa":"ケパ・アリサバラガ","nameEn":"Kepa Arrizabalaga","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:チェルシー・2025年7月"},
  {"key":"setford","nameJa":"トミー・セットフォード","nameEn":"Tommy Setford","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:アヤックス(下部組織)・2024年7月"},
  {"key":"porter","nameJa":"ジャック・ポーター","nameEn":"Jack Porter","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"ranson","nameJa":"カリ・ランソン","nameEn":"Khari Ranson","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"homegrown"},
  {"key":"meslier","nameJa":"イラン・メリエ","nameEn":"Illan Meslier","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"フリー移籍・前所属:リーズ・ユナイテッド・2026年7月"},
  {"key":"saliba","nameJa":"ウィリアン・サリバ","nameEn":"William Saliba","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:サンテティエンヌ・2019年7月"},
  {"key":"mosquera","nameJa":"クリスティアン・モスケラ","nameEn":"Cristhian Mosquera","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:バレンシアCF・2025年7月"},
  {"key":"white","nameJa":"ベン・ホワイト","nameEn":"Ben White","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:ブライトン・2021年7月"},
  {"key":"gabriel","nameJa":"ガブリエウ・マガリャンイス","nameEn":"Gabriel Magalhães","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:リールOSC・2020年9月"},
  {"key":"timber","nameJa":"ユリエン・ティンバー","nameEn":"Jurriën Timber","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:アヤックス・2023年7月"},
  {"key":"calafiori","nameJa":"リッカルド・カラフィオーリ","nameEn":"Riccardo Calafiori","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:ボローニャ・2024年7月"},
  {"key":"dixon","nameJa":"ジェイデン・ディクソン","nameEn":"Jaden Dixon","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"undisclosed・前所属:ストーク・シティ・2026年2月"},
  {"key":"salmon","nameJa":"マルリ・サーモン","nameEn":"Marli Salmon","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"hincapie","nameJa":"ピエロ・インカピエ","nameEn":"Piero Hincapié","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:バイエル・レバークーゼン・2026年6月"},
  {"key":"odegaard","nameJa":"マルティン・ウーデゴール","nameEn":"Martin Ødegaard","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:レアル・ソシエダ経由レアル・マドリード・2021年8月"},
  {"key":"eze","nameJa":"エベレチ・エゼ","nameEn":"Eberechi Eze","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:クリスタル・パレス・2025年8月"},
  {"key":"norgaard","nameJa":"クリスティアン・ノアゴール","nameEn":"Christian Nørgaard","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:ブレントフォード・2025年7月"},
  {"key":"vieira","nameJa":"ファビオ・ビエイラ","nameEn":"Fábio Vieira","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:ポルト・2022年6月"},
  {"key":"merino","nameJa":"ミケル・メリーノ","nameEn":"Mikel Merino","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:レアル・ソシエダ・2024年8月"},
  {"key":"zubimendi","nameJa":"マルティン・スビメンディ","nameEn":"Martín Zubimendi","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:レアル・ソシエダ・2025年7月"},
  {"key":"rice","nameJa":"デクラン・ライス","nameEn":"Declan Rice","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:ウェストハム・2023年7月"},
  {"key":"lewisskelly","nameJa":"マイルズ・ルイス＝スケリー","nameEn":"Myles Lewis-Skelly","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"homegrown"},
  {"key":"dowman","nameJa":"マックス・ダウマン","nameEn":"Max Dowman","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"harrimanannous","nameJa":"アンドレ・ハリマン・アンヌース","nameEn":"Andre Harriman-Annous","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"ifeibrahim","nameJa":"イフェ・イブラヒム","nameEn":"Ife Ibrahim","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"saka","nameJa":"ブカヨ・サカ","nameEn":"Bukayo Saka","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"homegrown"},
  {"key":"jesus","nameJa":"ガブリエウ・ジェズス","nameEn":"Gabriel Jesus","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:マンチェスター・シティ・2022年7月"},
  {"key":"martinelli","nameJa":"ガブリエウ・マルティネッリ","nameEn":"Gabriel Martinelli","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:イトゥアーノ・2019年7月"},
  {"key":"gyokeres","nameJa":"ヴィクトル・ギェケレシュ","nameEn":"Viktor Gyökeres","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:スポルティングCP・2025年7月"},
  {"key":"tzolis","nameJa":"クリストス・ツォリス","nameEn":"Christos Tzolis","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"fee・前所属:クラブ・ブルージュ・2026年7月"},
  {"key":"madueke","nameJa":"ノニ・マドゥエケ","nameEn":"Noni Madueke","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"fee・前所属:チェルシー・2025年7月"},
  {"key":"nwaneri","nameJa":"イーサン・ヌワネリ","nameEn":"Ethan Nwaneri","clubJa":"アーセナルFC","staticFoot":"左足","staticContractNote":"homegrown"},
  {"key":"nelson","nameJa":"リース・ネルソン","nameEn":"Reiss Nelson","clubJa":"アーセナルFC","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"havertz","nameJa":"カイ・ハフェルツ","nameEn":"Kai Havertz","clubJa":"アーセナルFC","staticFoot":"両足","staticContractNote":"fee・前所属:チェルシー・2023年6月"},
  {"key":"sagoe","nameJa":"チャールズ・サゴエ・ジュニア","nameEn":"Charles Sagoe Jr","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"oneill","nameJa":"シーダック・オニール","nameEn":"Ceadach O'Neill","clubJa":"アーセナルFC","staticFoot":"右足","staticContractNote":"undisclosed・前所属:リンフィールドFC(北アイルランド)・2023年11月"},
  {"key":"baileyjoseph","nameJa":"ブランド・ベイリー・ジョセフ","nameEn":"Brando Bailey-Joseph","clubJa":"アーセナルFC","staticFoot":"不明","staticContractNote":"homegrown"},
  {"key":"courtois","nameJa":"ティボー・クルトワ","nameEn":"Thibaut Courtois","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:チェルシー・2018年8月"},
  {"key":"lunin","nameJa":"アンドリー・ルーニン","nameEn":"Andriy Lunin","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:ゾーリャ・ルハンシク・2018年7月"},
  {"key":"militao","nameJa":"エデル・ミリトン","nameEn":"Éder Militão","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:ポルト・2019年7月"},
  {"key":"trent","nameJa":"トレント・アレクサンダー=アーノルド","nameEn":"Trent Alexander-Arnold","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:リバプール・2025年7月"},
  {"key":"asencio","nameJa":"ラウル・アセンシオ","nameEn":"Raúl Asencio","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"carreras","nameJa":"アルバロ・カレーラス","nameEn":"Álvaro Carreras","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:ベンフィカ・2025年7月"},
  {"key":"rudigerrm","nameJa":"アントニオ・リュディガー","nameEn":"Antonio Rüdiger","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:チェルシー・2022年7月"},
  {"key":"mendyrm","nameJa":"フェルラン・メンディ","nameEn":"Ferland Mendy","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:リヨン・2019年6月"},
  {"key":"huijsen","nameJa":"ディーン・ハウゼン","nameEn":"Dean Huijsen","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:AFCボーンマス・2025年7月"},
  {"key":"dumfries","nameJa":"デンゼル・ダンフリース","nameEn":"Denzel Dumfries","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:インテル・ミラン・2026年夏"},
  {"key":"konate","nameJa":"イブラヒマ・コナテ","nameEn":"Ibrahima Konaté","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"フリー移籍・前所属:リバプール・2026年夏"},
  {"key":"cucurella","nameJa":"マルク・ククレジャ","nameEn":"Marc Cucurella","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:チェルシー・2026年夏"},
  {"key":"bellingham","nameJa":"ジュード・ベリンガム","nameEn":"Jude Bellingham","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:ボルシア・ドルトムント・2023年6月"},
  {"key":"camavinga","nameJa":"エドゥアルド・カマヴィンガ","nameEn":"Eduardo Camavinga","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:スタッド・レンヌ・2021年8月"},
  {"key":"valverde","nameJa":"フェデリコ・バルベルデ","nameEn":"Federico Valverde","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:ペニャロール・2016年7月(加入後レンタルを経てトップチーム昇格)"},
  {"key":"tchouameni","nameJa":"オレリアン・チュアメニ","nameEn":"Aurélien Tchouaméni","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:モナコ・2022年6月"},
  {"key":"guler","nameJa":"アルダ・ギュレル","nameEn":"Arda Güler","clubJa":"レアル・マドリード","staticFoot":"左足","staticContractNote":"fee・前所属:フェネルバフチェ・2023年7月"},
  {"key":"brahim","nameJa":"ブラヒム・ディアス","nameEn":"Brahim Díaz","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"homegrown・前所属:マンチェスター・シティ・2019年7月"},
  {"key":"vinicius","nameJa":"ヴィニシウス・ジュニオール","nameEn":"Vinícius Júnior","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:フラメンゴ・2018年7月(加入後レンタルを経てトップチーム昇格)"},
  {"key":"rodrygo","nameJa":"ホドリゴ","nameEn":"Rodrygo","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:サントス・2019年7月"},
  {"key":"gonzalogarcia","nameJa":"ゴンサロ・ガルシア","nameEn":"Gonzalo García","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"homegrown"},
  {"key":"mastantuono","nameJa":"フランコ・マスタントゥオーノ","nameEn":"Franco Mastantuono","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:リベル・プレート・2025年8月"},
  {"key":"endrick","nameJa":"エンドリッキ","nameEn":"Endrick","clubJa":"レアル・マドリード","staticFoot":"右足","staticContractNote":"fee・前所属:パルメイラス・2022年12月(2024年加入)"}
];

module.exports = { REGISTERED_PLAYERS };
